version: "3.8"

x-app: &x-app
  working_dir: /app
  volumes:
    - ./:/app

services:
  py:
    image: python:3
    command: ./scripts/run-tests-all.sh references/py3.8/*requirements.txt
    <<: *x-app

  py3.8:
    image: python:3.8
    command: ./scripts/run-tests-all.sh references/py3.8/*requirements.txt
    <<: *x-app

  py2.7:
    image: python:2.7
    command: ./scripts/run-tests-all.sh references/py2.7/*requirements.txt
    <<: *x-app
