version: "3.8"

x-app: &x-app
  working_dir: /app
  volumes:
    - ./:/app

services:
  app-test-py:
    image: python:3
    command: ./scripts/run-tests-all.sh references/py3.8/*requirements.txt
    <<: *x-app

  app-test-py3.8:
    image: python:3.8-buster
    command: ./scripts/run-tests-all.sh references/py3.8/*requirements.txt
    <<: *x-app

  app-test-py2.7.11:
    image: python:2.7
    command: ./scripts/run-tests-all.sh references/py2.7/*requirements.txt
    <<: *x-app
